"""init

Revision ID: 7b72c485a1c7
Revises: 
Create Date: 2023-11-22 16:14:06.009952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b72c485a1c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('advice_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('birth_date', sa.String(length=128), nullable=True),
    sa.Column('horoscope_text_index', sa.Integer(), nullable=True),
    sa.Column('apply_code', sa.String(length=16), nullable=True),
    sa.Column('got_2h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_24h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_48h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_72h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('bf_state', sa.String(length=64), nullable=True),
    sa.Column('bf_22nov', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
