"""comment

Revision ID: b0f6ac254352
Revises: 7b72c485a1c7
Create Date: 2024-02-29 01:47:18.157716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f6ac254352'
down_revision = '7b72c485a1c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_29_feb', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_29_feb')
    # ### end Alembic commands ###
