"""empty message

Revision ID: b8ea423636ae
Revises: 0e709d3d41bb
Create Date: 2024-04-24 14:17:09.075357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ea423636ae'
down_revision = '0e709d3d41bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_24_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_24_april')
    # ### end Alembic commands ###
