"""init

Revision ID: 0e709d3d41bb
Revises: 3eb251dea0b5
Create Date: 2024-04-04 06:31:33.207580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e709d3d41bb'
down_revision = '3eb251dea0b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_4_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_4_april')
    # ### end Alembic commands ###
